Repository Sub-game-team/Subgame, pull requests merged in 2023-11, with the labels that each got.

#15 Movement fix
  CharacterBody2DMovement.gd
Labels: documentation, good first issue

#17 Scenes
  CharacterBody2DMovement.gd
  character_body_2d.tscn
  node_2d.tscn
  sprite_2d_2.tscn
  tile_map.tscn
Labels: documentation, help wanted

#16 Wall collison
  CharacterBody2DMovement.gd
  node_2d.tscn
Labels: documentation

#19 Updated the scene stuff and added a mob
  character_body_2d.tscn
  enemy_normal.png
  enemy_normal.png.import
  main.gd
  main.tscn
  mob.gd
  mob_scene.tscn
  node_2d.tscn
  player.tscn
  project.godot
  sprite_2d_2.tscn
  tile_map.tscn
Labels: documentation, enhancement

#21 Update torpedo stuff
  character_body_2d.tscn
  enemy_normal.png
  enemy_normal.png.import
  main.gd
  main.tscn
  mob.gd
  mob_scene.tscn
  node_2d.tscn
  player.tscn
  project.godot
  sprite_2d_2.tscn
  tile_map.tscn
Labels: enhancement

#22 Added a camera zoom that works just fine.
  CharacterBody2DMovement.gd
  player.tscn
  player_camera.gd
  project.godot
Labels: documentation, enhancement

#28 Add files via upload
  Art/blue_water_ecxample.png
  Art/blue_water_v0.png
  Art/blue_water_v1.png
  Art/blue_water_v2.png
  Art/navy_water_ecxample.png
  Art/navy_water_v0.png
  Art/navy_water_v1.png
  Art/navy_water_v2.png
Labels: Art

#41 Add torpedo sprite
  Art/torpedo_0.png
Labels: Art, documentation

#42 Get Torpedo sprite
  Art/torpedo_0.png
Labels: invalid

#34 Idk why all the files got added I only fixed the camera zoom hopefully its okay
  Art/blue_water_ecxample.png.import
  Art/blue_water_v0.png.import
  Art/blue_water_v1.png.import
  Art/blue_water_v2.png.import
  Art/navy_water_ecxample.png.import
  Art/navy_water_v0.png.import
  Art/navy_water_v1.png.import
  Art/navy_water_v2.png.import
  player_camera.gd
Labels: bug, documentation

#35 Torpedos
  CharacterBody2DMovement.gd
  Torpedo.tscn
  Torpedo_normal.gd
  mob.gd
  mob_scene.tscn
  player.tscn
  project.godot
Labels: documentation, enhancement

#49 Add files via upload
  Art/torpedo_1.png
  Art/torpedo_2.png
  Art/torpedo_3.png
Labels: Art

#53 Update branch to get torpedo
  Art/torpedo_1.png
  Art/torpedo_2.png
  Art/torpedo_3.png
Labels: invalid
