Repository Sub-game-team/Subgame, pull requests merged in 2024-01, with the labels that each got.

#94 Filesystem
  Player.gd
  Savegames/save1.save
  Savegames/settings.save
  Torpedo_menu.gd
  main.gd
  main.tscn
  main_menu.gd
  main_menu.tscn
  mob.gd
  player.tscn
  project.godot
Labels: documentation, enhancement

#97 Add files via upload
  Art/drone.png
  Art/drone_ohne.png
Labels: Art

#100 Add files via upload
  Content.png
Labels: duplicate
